---
name: ci-gradle-nexus

on:
  workflow_call:
    inputs:
      publish_snapshots:
        description: Whether to attempt publishing snapshots. When false, the workflow will only run build.
        type: boolean
        default: true
        required: false
    secrets:
      nexus_username:
        required: true
      nexus_password:
        required: true

env:
  GRADLE_SWITCHES: --console=plain --info --stacktrace --warning-mode=all 
  NEXUS_USERNAME: ${{ secrets.nexus_username }}
  NEXUS_PASSWORD: ${{ secrets.nexus_password }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Build
        run: ./gradlew ${{ env.GRADLE_SWITCHES }} build
      
      - name: Publish Snapshots
        if: inputs.publish_snapshots && github.event_name != 'pull_request'
        run: ./gradlew ${{ env.GRADLE_SWITCHES }} publish
        env:
          NEXUS_USERNAME: ${{ secrets.nexus_username }}
          NEXUS_PASSWORD: ${{ secrets.nexus_password }}
